settings:
  min-bots: 4                # Минимальный фейк-онлайн
  max-bots: 12               # Максимальный фейк-онлайн
  show-join-messages: true   # Сообщения о входе ботов в чат
  show-quit-messages: true   # Сообщения о выходе ботов в чат

messages:
  join: "&e%player% зашел на сервер."
  quit: "&e%player% покинул сервер."

# Реалистичные ники СНГ игроков
bot-names:
  - "Fixik_Play"
  - "Mr_Donut"
  - "Keksik33"
  - "Tvoy_Koshmar"
  - "Zero_Cool"
  - "Pro_Gamer_RU"
  - "Alinka_Malinka"
  - "Danya_Top"
  - "Sanya_Shaxat"
  - "Noobik_v_almaze"
  - "Dark_Rider"
  - "Kotik_Наркотик"
  - "Vlad_Bros"
  - "Skil_Игрок"
  - "Panda_Gamer"
  - "Mistik_Fan"
  - "Lego_Man"

# Живые фразы (боты будут писать их редко, раз в 10-20 минут)
chat-phrases:
  - "всем ку"
  - "ку всем"
  - "кто приютит? я адекват"
  - "где тут шахту найти нормальную?"
  - "пвп кто на спавне?"
  - "админ чекни репорт плз"
  - "а тут есть донат за квесты?"
  - "кто тим? пишите в лс"
  - "жесть у меня лагануло щас"
  - "какой максимальный приват тут?"
  - "ку"
  - "как сделать приват регион?"
  - "пойду за деревом"